import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="max-w-screen-xl mx-auto bg-black text-white">
        {children}
      </body>
    </html>
  )
}
