import { Metadata } from "next";
import "./globals.css";
import MainSideBar from "@/components/main-side-bar";
import SearchBar from "@/components/search-bar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="w-screen h-screen flex">
        <MainSideBar />
        <div className="w-full relative">
          <SearchBar />
          <main className="w-full">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
